#!/usr/bin/env bash
#
# Ace Cast — one-shot server bootstrap for a fresh Ubuntu 24.04 Linode (SQLite stack).
#
# Runs everything on the box: system update, firewall, Docker, clone, and launch the
# SQLite Compose stack behind Caddy (auto-HTTPS). Idempotent — safe to re-run to update.
#
# Use it either way:
#   A) After creating the Linode, from your laptop:
#        ssh root@<LINODE_IP> "DOMAIN=unholy.cards REPO_URL=https://github.com/<you>/ace-cast.git GIT_REF=main bash -s" < bootstrap.sh
#   B) As a Linode StackScript: paste this file, set the vars below, deploy at create time.
#
# NOTE: point your domain's A record at this box's IP. Caddy will keep retrying the TLS
# cert until DNS resolves, so order isn't fatal — but DNS-first is cleaner.
set -euo pipefail

# ---- configure (or pass as env vars) --------------------------------------
DOMAIN="${DOMAIN:-unholy.cards}"
REPO_URL="${REPO_URL:-https://github.com/CHANGE-ME/ace-cast.git}"
GIT_REF="${GIT_REF:-main}"          # branch/tag/sha to deploy (include F2 for flagging)
APP_DIR="${APP_DIR:-/opt/ace-cast}"
# ---------------------------------------------------------------------------

log() { echo ">> $*"; }

log "system update"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y git ca-certificates curl ufw openssl

log "firewall: ssh + web only"
ufw allow OpenSSH >/dev/null 2>&1 || true
ufw allow 80/tcp  >/dev/null 2>&1 || true
ufw allow 443/tcp >/dev/null 2>&1 || true
ufw --force enable >/dev/null 2>&1 || true

log "docker"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker

log "clone / update repo at $APP_DIR (ref: $GIT_REF)"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" checkout "$GIT_REF"
  git -C "$APP_DIR" pull --ff-only origin "$GIT_REF" || true
else
  git clone "$REPO_URL" "$APP_DIR"
  git -C "$APP_DIR" checkout "$GIT_REF"
fi

log "write deploy/.env (domain + generated secrets; idempotent)"
ENV_FILE="$APP_DIR/deploy/linode/.env"

# Reuse a secret already in .env, else mint a fresh one. Re-runs must NOT rotate
# these: changing AUTHELIA_STORAGE_ENCRYPTION_KEY orphans Authelia's encrypted
# store, and changing the session secrets logs everyone out. Compute values
# BEFORE truncating the file (the heredoc below overwrites it).
existing_env() { [ -f "$ENV_FILE" ] && sed -n "s/^$1=//p" "$ENV_FILE" | head -1 || true; }
keep_or_gen() { local cur; cur="$(existing_env "$1")"; if [ -n "$cur" ]; then printf '%s' "$cur"; else openssl rand -hex 32; fi; }

ADMIN_TOKEN_V="$(keep_or_gen ADMIN_TOKEN)"
AUTH_SESSION_SECRET_V="$(keep_or_gen AUTH_SESSION_SECRET)"
AUTHELIA_JWT_SECRET_V="$(keep_or_gen AUTHELIA_JWT_SECRET)"
AUTHELIA_SESSION_SECRET_V="$(keep_or_gen AUTHELIA_SESSION_SECRET)"
AUTHELIA_STORAGE_ENCRYPTION_KEY_V="$(keep_or_gen AUTHELIA_STORAGE_ENCRYPTION_KEY)"

cat > "$ENV_FILE" <<EOF
SITE_ADDRESS=$DOMAIN
PUBLIC_URL=https://$DOMAIN
# F3 feedback dashboard admin gate (single shared token): /admin/feedback?token=...
ADMIN_TOKEN=$ADMIN_TOKEN_V
# E4 accounts — app session + Authelia secrets. Never commit this file.
AUTH_SESSION_SECRET=$AUTH_SESSION_SECRET_V
AUTHELIA_JWT_SECRET=$AUTHELIA_JWT_SECRET_V
AUTHELIA_SESSION_SECRET=$AUTHELIA_SESSION_SECRET_V
AUTHELIA_STORAGE_ENCRYPTION_KEY=$AUTHELIA_STORAGE_ENCRYPTION_KEY_V
EOF
chmod 600 "$ENV_FILE"

# Authelia needs a real user; the committed users_database.example.yml only holds a
# placeholder hash it would refuse to boot on. Generate a proper admin into the
# gitignored users_database.yml on first run (skipped if it already exists, so a
# re-run never clobbers your users). Override with ADMIN_USER/ADMIN_PASSWORD/ADMIN_EMAIL.
USERS_FILE="$APP_DIR/deploy/linode/authelia/users_database.yml"
ADMIN_CREATED=""
if [ ! -f "$USERS_FILE" ]; then
  ADMIN_USER="${ADMIN_USER:-admin}"
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -base64 15)}"
  log "generating Authelia admin '$ADMIN_USER' (argon2id)"
  ADMIN_HASH="$(docker run --rm authelia/authelia:4.38 \
    authelia crypto hash generate argon2 --password "$ADMIN_PASSWORD" 2>/dev/null \
    | sed -n 's/^Digest: //p')"
  if [ -n "$ADMIN_HASH" ]; then
    cat > "$USERS_FILE" <<EOF
# Generated by bootstrap.sh on first run — NOT committed. Add more users here;
# hash a new password with:
#   docker compose -f docker-compose.sqlite.yml run --rm authelia \\
#     authelia crypto hash generate argon2 --password 'new-password'
users:
  $ADMIN_USER:
    displayname: '$ADMIN_USER'
    password: '$ADMIN_HASH'
    email: '$ADMIN_EMAIL'
    groups:
      - admins
EOF
    ADMIN_CREATED=1
  else
    log "!! could not hash automatically — seeding the example; set a real hash per runbook §11b before /account works"
    cp "$APP_DIR/deploy/linode/authelia/users_database.example.yml" "$USERS_FILE"
  fi
fi

log "launch SQLite stack (build + up)"
cd "$APP_DIR/deploy/linode"
docker compose -f docker-compose.sqlite.yml up -d --build

log "waiting for the app to answer locally..."
for _ in $(seq 1 30); do
  if curl -fsS "http://localhost:80/healthz" >/dev/null 2>&1 \
     || docker compose -f docker-compose.sqlite.yml exec -T app \
          node -e "require('http').get('http://localhost:3000/healthz',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))" >/dev/null 2>&1; then
    log "app is up"
    break
  fi
  sleep 2
done

cat <<EOF

Ace Cast bootstrapped.
  Domain : $DOMAIN   (ensure its A record points at this box's public IP)
  Check  : curl -s https://$DOMAIN/healthz   ->  {"status":"ok","db":true,...}
  Logs   : cd $APP_DIR/deploy/linode && docker compose -f docker-compose.sqlite.yml logs -f

  Feedback dashboard : https://$DOMAIN/admin/feedback?token=$ADMIN_TOKEN_V
Caddy fetches the TLS cert on first request once DNS resolves; give it a minute.
EOF

if [ -n "$ADMIN_CREATED" ]; then
  cat <<EOF

  ┌─ Authelia admin (SAVE THIS — shown only once) ────────────────
  │  Sign in at : https://$DOMAIN/account
  │  Username   : $ADMIN_USER
  │  Password   : $ADMIN_PASSWORD
  └───────────────────────────────────────────────────────────────
  Add/rotate users in $USERS_FILE (see runbook §11b).
EOF
fi
